// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using BlogMedia.Data;

#nullable disable

namespace BlogMedia.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260701202041_SeedingInitialData")]
    partial class SeedingInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlogMedia.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Technology"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Heath"
                        },
                        new
                        {
                            Id = 3,
                            Name = "LifeStyle"
                        });
                });

            modelBuilder.Entity("BlogMedia.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CommentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("BlogMedia.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FeatureImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Maksud Mubin",
                            CategoryId = 1,
                            Content = "Artificial intelligence (AI) is rapidly transforming the way we live and work. From self-driving cars to virtual assistants, AI is becoming an integral part of our daily lives. In this article, we will explore the future of AI and how it is changing the world.",
                            FeatureImagePath = "tech_image.jpg",
                            PublishDate = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Future of AI: How Artificial Intelligence is Changing the World"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Afsin Binte",
                            CategoryId = 2,
                            Content = "A healthy lifestyle includes eating balanced meals, exercising regularly, and maintaining proper hydration.",
                            FeatureImagePath = "health_image.jpg",
                            PublishDate = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "How To Eat Healthy"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Nahar",
                            CategoryId = 3,
                            Content = "Japanese cuisine is famous for its fresh ingredients, unique flavors, and artistic presentation.",
                            FeatureImagePath = "lifestyle_image.jpg",
                            PublishDate = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Exploring Japanese Cuisine"
                        });
                });

            modelBuilder.Entity("BlogMedia.Models.Comment", b =>
                {
                    b.HasOne("BlogMedia.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("BlogMedia.Models.Post", b =>
                {
                    b.HasOne("BlogMedia.Models.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BlogMedia.Models.Category", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("BlogMedia.Models.Post", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
